name: switchpayment
description: Switch Payment SDK
repository: https://github.com/jigskshah/switchpayment
version: 1.0.0+1

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_plugin_android_lifecycle: ^2.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: io.flutter.plugins.switchpayment
        pluginClass: MainActivityPlugin

topics:
  - android
  - plugin-development